### PR TITLE
optimize docker & add python extension

### PR DESCRIPTION
**Pull request by itzKassem**

### CODE REVIEW

**Comment by SauravDharwadkar** [comment]
docker running ubuntu  now i've planned to shift alpine , also using deb file (code server install script ) doesn't give more control and it doesn't support alpine .

**Comment by SauravDharwadkar** [comment]
Also repository mark as template , and feel free to fork and add own / plugins that require t your specific flow , i added some general but if you using this repo , that mean you have some cs skill so you can modify docker as per your own need

**Comment by itzKassem** [comment]
yeh but considre using latest amd64 code-server
+ the script has auto detection for linux distro it should work with alpine

**Comment by Cremesis** [comment]
Maybe you should create 2 different PRs? @KassemSYR

**Comment by SauravDharwadkar** [comment]
for now not making any changes , 
fork repo and add apt installs and code-server plugins and customize your own code-server

**Pull request closed without merging**
